# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            East Tennessee Helene Response
tagline:          'Resources, updates, data collection, mapping'
description:      'Maintained by  Tri Cities Mutual Aid'
url:              https://etn-helene-response.github.io
baseurl:          /

author:
  name:           'Tri Cities Mutual Aid'
  url:            https://www.facebook.com/groups/tricitiesmutualaid

 #paginate:         5

# Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
#gems: [jekyll-paginate]
