# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'East Tennessee Helene Response'
tagline:          'Data and Updates'
description:      'made by tri city mutual aid'
#url:              /
baseurl:          https://etn-helene-response.github.io/

author:
  name:           'tri city mutual aid'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/etn-helene-response
